#! /bin/sh

#====AUTOSTART====#

#if [[($xrandr -q | grep DP1-3 'DP1-3 connected') ]]; then
# xrandr --output eDP1 --primary --mode 1366x768 --rotate normal --output DP1-3 --mode 1920x1080 --rotate normal --right-of eDP1
#fi

mpd && mpc update &
#battery-monitor &
numlockx &
udiskie --tray &
nitrogen --restore &
nm-applet &
# compton &
setxkbmap pl &
$HOME/.config/polybar/launch.sh &
dunst &
xsetroot -cursor_name left_ptr &
sxhkd &

if [[ $(xrandr -q | grep 'DP1-3 connected') ]]; then
	xrandr --output eDP1 --primary --mode 1366x768 --rotate normal --output DP1-3 --mode 1920x1080 --rotate normal --right-of eDP1
fi

if [[ $(xrandr -q | grep 'HDMI1 connected') ]]; then
	xrandr --output eDP1 --primary --mode 1366x768 --rotate normal --output HDMI1 --mode 1920x1080i --rotate normal --right-of eDP1
fi

#====CONFIG====#

#bspc monitor -d I II III IV V VI VII 
bspc monitor eDP1 -d I II III IV V VI VII
bspc monitor DP1-3 -d VIII IX
#bspc monitor eDP1 -d I II III IV
bspc monitor HDMI1 -d VIII IX

bspc config border_width         3
bspc config normal_border_color "#1a1d23"
bspc config focused_border_color "#656e7f"
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

#====Rules====#

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
#bspc rule -a Steam desktop='^6'
bspc rule -a TelegramDesktop desktop='^7'
bspc rule -a Docky layer=above manage=on border=off
#bspc rule -a firefox desktop='^1'
#bspc rule -a Pcmanfm desktop='3'
